import "./globals.css";
import { Inter } from "next/font/google";
import { Bebas_Neue } from "next/font/google"; // Import with underscore
import { Poppins } from "next/font/google"; // Import with underscore
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400", // Bebas Neue only has one weight (Regular: 400)
  display: "swap",
  variable: "--font-bebas-neue", // Define your CSS variable
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400", // Poppins has multiple weights, but we'll use Regular: 400
  display: "swap",
  variable: "--font-poppins", // Define your CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={[bebas_neue.variable, "bg-[#101011]"].join(" ")}>
      <body className={`${inter.className} ${poppins.variable}`}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
